#!/usr/bin/env node
/**
 * Release staging for RLM — produces `dist/release/<platform-tag>/` with:
 * - `dist/`    — TypeScript compilation output mirrored from repo `dist/` (includes `dist/src`).
 * - `ui-dist/` — Vite UI static assets (from repo `ui/dist` after build).
 * - `rlm`      — Unix shim: invokes `node` + `dist/src/index.js`; leaves process cwd unchanged (D-10-07).
 * - `rlm.cmd`  — Windows shim equivalent.
 *
 * Folder names inside `dist/release/` use Node’s `process.platform` + `process.arch`, e.g.:
 * `linux-x64`, `darwin-arm64`, `win32-x64`.
 *
 * The script runs `npm run build` then `npm run build:ui` from the repo root, then writes only under
 * `./dist/release/<tag>/` (no deletes outside that subtree).
 */

import { cpSync, existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..", "..");

function run(cmd, argv, opts = {}) {
  const result = spawnSync(cmd, argv, {
    cwd: ROOT,
    stdio: "inherit",
    shell: process.platform === "win32",
    ...opts,
  });
  if (result.error) {
    throw result.error;
  }
  if (result.status !== 0) {
    process.exit(result.status ?? 1);
  }
}

const npmCmd = process.platform === "win32" ? "npm.cmd" : "npm";
run(npmCmd, ["run", "build"]);
run(npmCmd, ["run", "build:ui"]);

const tag = `${process.platform}-${process.arch}`;
const outRoot = resolve(ROOT, "dist", "release", tag);

const srcDist = resolve(ROOT, "dist");
const srcUiDist = resolve(ROOT, "ui", "dist");
const srcEnsureOllama = resolve(ROOT, "scripts", "desktop", "ensure-ollama.mjs");

if (!existsSync(srcDist)) {
  console.error("Expected build output missing: dist/");
  process.exit(1);
}
if (!existsSync(srcUiDist)) {
  console.error("Expected UI build output missing: ui/dist/");
  process.exit(1);
}

mkdirSync(outRoot, { recursive: true });
const stagedDist = join(outRoot, "dist");
mkdirSync(stagedDist, { recursive: true });
copyDistTreeExcludingRelease(srcDist, stagedDist);
cpSync(srcUiDist, join(outRoot, "ui-dist"), { recursive: true });
cpSync(srcEnsureOllama, join(outRoot, "ensure-ollama.mjs"));

const launcherHeader =
  "; This file is generated by scripts/packaging/build-release.mjs — do not hand-edit packaged copies.\r\n";

const entryRel = ["dist", "src", "index.js"].join("/");
const unixSh = [
  "#!/usr/bin/env sh",
  `# RLM shim — invokes Node against packaged ${entryRel}`,
  'SCRIPT_ROOT="$(CDPATH="" cd "$(dirname "$0")" && pwd)"',
  'NODE_EXE="${NODE_BINARY:-node}"',
  `exec "$NODE_EXE" "$SCRIPT_ROOT/${entryRel}" "$@"`,
  "",
].join("\n");

writeFileSync(join(outRoot, "rlm"), unixSh, { mode: 0o755 });

const winSh = [
  launcherHeader,
  "@echo off",
  "setlocal",
  "set \"SCRIPT_ROOT=%~dp0\"",
  "set \"SCRIPT_ROOT=%SCRIPT_ROOT:~0,-1%\"",
  `node "%SCRIPT_ROOT%\\dist\\src\\index.js" %*`,
  "",
].join("\r\n");
writeFileSync(join(outRoot, "rlm.cmd"), winSh);

writeFileSync(join(outRoot, "desktop-manifest.json"), JSON.stringify({
  name: "recursive-language-model",
  version: readPackageVersion(),
  platform: process.platform,
  arch: process.arch,
  entry: "dist/src/index.js",
  uiDist: "ui-dist",
  launch: {
    unix: "./rlm ui",
    windows: "rlm.cmd ui",
  },
  ollama: {
    check: "node ensure-ollama.mjs",
    managedStartEnv: "RLM_MANAGE_OLLAMA=1",
  },
}, null, 2));

console.error(`Release staged at ${outRoot}`);

function readPackageVersion() {
  const pkg = JSON.parse(readFileSync(resolve(ROOT, "package.json"), "utf8"));
  return pkg.version ?? "0.0.0";
}

/**
 * @param {string} srcDir
 * @param {string} destDir
 */
function copyDistTreeExcludingRelease(srcDir, destDir) {
  for (const name of readdirSync(srcDir)) {
    if (name === "release") {
      continue;
    }

    const from = join(srcDir, name);
    const to = join(destDir, name);
    cpSync(from, to, { recursive: true });
  }
}
