#!/usr/bin/env node
/**
 * Release staging for RLM — produces `dist/release/<platform-tag>/` with:
 * - `rlm`      — Rust CLI binary (control server + CLI entry)
 * - `ui-dist/` — Vite UI static assets (from repo `ui/dist` after build)
 * - `rlm.cmd`  — Windows launcher shim
 *
 * Folder names inside `dist/release/` use Node’s `process.platform` + `process.arch`, e.g.:
 * `linux-x64`, `darwin-arm64`, `win32-x64`.
 *
 * The script runs `npm run build:ui`, `cargo build --release -p rlm-cli`, then writes only under
 * `./dist/release/<tag>/` (no deletes outside that subtree).
 */

import { chmodSync, cpSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..", "..");

function run(cmd, argv, opts = {}) {
  const result = spawnSync(cmd, argv, {
    cwd: ROOT,
    stdio: "inherit",
    shell: process.platform === "win32",
    ...opts,
  });
  if (result.error) {
    throw result.error;
  }
  if (result.status !== 0) {
    process.exit(result.status ?? 1);
  }
}

const npmCmd = process.platform === "win32" ? "npm.cmd" : "npm";
run(npmCmd, ["run", "build:ui"]);
run("cargo", ["build", "--release", "-p", "rlm-cli"]);

const tag = `${process.platform}-${process.arch}`;
const outRoot = resolve(ROOT, "dist", "release", tag);

const srcUiDist = resolve(ROOT, "ui", "dist");
const rustBinaryName = process.platform === "win32" ? "rlm.exe" : "rlm";
const rustBinarySrc = resolve(ROOT, "target", "release", rustBinaryName);

if (!existsSync(srcUiDist)) {
  console.error("Expected UI build output missing: ui/dist/");
  process.exit(1);
}
if (!existsSync(rustBinarySrc)) {
  console.error(`Expected Rust binary missing: target/release/${rustBinaryName}`);
  process.exit(1);
}

mkdirSync(outRoot, { recursive: true });
cpSync(rustBinarySrc, join(outRoot, rustBinaryName));
if (process.platform !== "win32") {
  chmodSync(join(outRoot, rustBinaryName), 0o755);
}
cpSync(srcUiDist, join(outRoot, "ui-dist"), { recursive: true });

const launcherHeader =
  "; This file is generated by scripts/packaging/build-release.mjs — do not hand-edit packaged copies.\r\n";

if (process.platform === "win32") {
  const winSh = [
    launcherHeader,
    "@echo off",
    "setlocal",
    "set \"SCRIPT_ROOT=%~dp0\"",
    "set \"SCRIPT_ROOT=%SCRIPT_ROOT:~0,-1%\"",
    `"%SCRIPT_ROOT%\\${rustBinaryName}" %*`,
    "",
  ].join("\r\n");
  writeFileSync(join(outRoot, "rlm.cmd"), winSh);
} else {
  const unixSh = [
    "#!/usr/bin/env sh",
    "# RLM launcher — invokes packaged Rust binary",
    'SCRIPT_ROOT="$(CDPATH="" cd "$(dirname "$0")" && pwd)"',
    `exec "$SCRIPT_ROOT/${rustBinaryName}" "$@"`,
    "",
  ].join("\n");
  writeFileSync(join(outRoot, "rlm"), unixSh, { mode: 0o755 });
}

writeFileSync(
  join(outRoot, "desktop-manifest.json"),
  JSON.stringify(
    {
      name: "recursive-language-model",
      version: readPackageVersion(),
      platform: process.platform,
      arch: process.arch,
      entry: rustBinaryName,
      uiDist: "ui-dist",
      runtime: {
        kind: "rust-binary",
        binary: rustBinaryName,
      },
      launch: {
        unix: "./rlm ui",
        windows: "rlm.cmd ui",
      },
      ollama: {
        check: "embedded-in-tauri",
        managedStartEnv: "RLM_MANAGE_OLLAMA=1",
      },
    },
    null,
    2,
  ),
);

console.error(`Release staged at ${outRoot}`);

function readPackageVersion() {
  const pkg = JSON.parse(readFileSync(resolve(ROOT, "package.json"), "utf8"));
  return pkg.version ?? "0.0.0";
}
